In [1]:
import numpy as np
import math 
import cmath
import abipy
from abipy.electrons.scr import ScrFile
import time
import matplotlib.pyplot as plt
import pointcloud as pc
from scipy.interpolate import RegularGridInterpolator
import plotly.graph_objects as go
%load_ext autoreload
%autoreload 2
import Fourier_tool as Ft
import XGChi0 
import MatrixCharacteristic

# Structure Part

## Slab classic :

filename : Al_Slab_nsym0o_DS1_SUS.nc (nsym0), Al_Slab_nsym1o_DS1_SUS.nc (nsym1)

nat_cellslab=4

Aslab=[2.017790474253013, -2.017790474253013, 0.0]

Bslab=[2.017790474253013, 2.017790474253013, 0.0]

Cslab=[0.0, 0.0, 14.124533319771093]

pos_redslab=np.array([[0.0000, 0.0000, -0.0060],
[-0.5000, 0.5000, 0.1369],
[0.0000, 0.0000, 0.2798],
[-0.5000, 0.5000, 0.4226]])

nkslab=[4,4,1]

XGChi0.Vis_tool(chi0rrslab, Rslab, Aslab, Bslab, Cslab, nkslab, nat_cellslab, pos_redslab, N=10000, isomin=3)

## Slab double void

filename : Al_Slab_dvo_DS1_SUS.nc

Aslab2 = [2.017790474253013, -2.017790474253013, 0.0]

Bslab2 = [2.017790474253013, 2.017790474253013, 0.0]

Cslab2 = [0.0, 0.0, 28.249066639542185]

pos_red_slab2 = np.array([[0.0000, -0.0000, -0.0071], [-0.5000, 0.5000, 0.0643], [0.0000, -0.0000, 0.1357], [-0.5000, 0.5000, 0.2071]])

nkslab2 = [4, 4, 1]

nat_cellslab2 = 4

XGChi0.Vis_tool(chi0rrslab2, Rslab2, Aslab2, Bslab2, Cslab2, nkslab2, nat_cellslab2, pos_red_slab2, N=10000, isomin=3)

## Bulk Prim

filename : Al_Bulk_nsym0o_DS1_SUS.nc (nsym0), Al_Bulk_nsym1o_DS1_SUS.nc (nsym1), Al_Bulk_eps17_SUS.nc (nsym0)

A = [1.6475190232561199, 0.0, 2.3299437469564794]

B = [-0.8237595116280599, 1.426793327357925, 2.3299437469564794]

C = [-0.8237595116280599, -1.426793327357925, 2.3299437469564794]

pos_red = np.array([[0, 0, 0]])

nat_cell = 1

nk = [4, 4, 4]

XGChi0.Vis_tool(chi0rr, R, A, B, C, nk, nat_cell, pos_red, N=10000, isomin=3)

## Bulk Prim nkpt 6 6 6 

filename : Al_Bulk_nkpt6o_DS1_SUS.nc (nsym0)

A = [1.6475190232561199, 0.0, 2.3299437469564794]

B = [-0.8237595116280599, 1.426793327357925, 2.3299437469564794]

C = [-0.8237595116280599, -1.426793327357925, 2.3299437469564794]

pos_red = np.array([[0, 0, 0]])

nat_cell = 1

nk6 = [6, 6, 6]

XGChi0.Vis_tool(chi0rr, R, A, B, C, nk6, nat_cell, pos_red, N=10000, isomin=3)

## Bulk Prim nkpt 8 8 8 

filename : Al_Bulk_nkpt8o_DS1_SUS.nc (nsym0, ecuteps6)

A = [1.6475190232561199, 0.0, 2.3299437469564794]

B = [-0.8237595116280599, 1.426793327357925, 2.3299437469564794]

C = [-0.8237595116280599, -1.426793327357925, 2.3299437469564794]

pos_red = np.array([[0, 0, 0]])

nat_cell = 1

nk8 = [8, 8, 8]

XGChi0.Vis_tool(chi0rr, R, A, B, C, nk8, nat_cell, pos_red, N=10000, isomin=3)

## Bulk Prim Ecuteps Conv (nband = 200)

filenames : Al_Bulk_nkpt4o_DS1_SUS.nc (ecuteps = 5), Al_Bulk_nkpt4o_DS2_SUS.nc (ecuteps = 9), Al_Bulk_nkpt4o_DS3_SUS.nc (ecuteps = 13), Al_Bulk_nkpt4o_DS4_SUS.nc (ecuteps = 17), Al_Bulk_nkpt4o_DS5_SUS.nc (ecuteps = 21)

A = [1.6475190232561199, 0.0, 2.3299437469564794]

B = [-0.8237595116280599, 1.426793327357925, 2.3299437469564794]

C = [-0.8237595116280599, -1.426793327357925, 2.3299437469564794]

pos_red = np.array([[0, 0, 0]])

nat_cell = 1

nk = [4, 4, 4]

XGChi0.Vis_tool(chi0rr, R, A, B, C, nk, nat_cell, pos_red, N=10000, isomin=3)

## Bulk Prim Nband Conv (ecuteps = 9)

filenames : Al_Bulk_nkpt4_nbando_DS1_SUS.nc (nband = 100), Al_Bulk_nkpt4_nbando_DS2_SUS.nc (nband = 150), Al_Bulk_nkpt4_nbando_DS3_SUS.nc (nband = 200), Al_Bulk_nkpt4_nbando_DS4_SUS.nc (nband = 250), Al_Bulk_nkpt4_nbando_DS5_SUS.nc (nband = 300)

A = [1.6475190232561199, 0.0, 2.3299437469564794]

B = [-0.8237595116280599, 1.426793327357925, 2.3299437469564794]

C = [-0.8237595116280599, -1.426793327357925, 2.3299437469564794]

pos_red = np.array([[0, 0, 0]])

nat_cell = 1

nk = [4, 4, 4]

XGChi0.Vis_tool(chi0rr, R, A, B, C, nk, nat_cell, pos_red, N=10000, isomin=3)

## Bulk Conv

filename : Al_Bulko_DS1_SUS.nc

D = [4.0389300176539065, 0.0, 0.0]

E = [2.4731313590500095e-16, 4.0389300176539065, 0.0]

F = [2.4731313590500095e-16, 2.4731313590500095e-16, 4.0389300176539065]

posred_conv = np.array([[0, 0, 0], [0, 0.5, 0.5], [0.5, 0, 0.5], [0.5, 0.5, 0]])

nat_cell_conv = 4

nkconv = [4, 4, 4]

XGChi0.Vis_tool(chi0rrconv, Rconv, D, E, F, nkconv, nat_cell_conv, posred_conv, N=10000, isomin=3)

# Slab 13 atoms

A = [2.017790474253013, -2.017790474253013, 0.0]

B = [2.017790474253013, 2.017790474253013, 0.0]

C = [0.0, 0.0, 32.28464758804821]

pos_redslab13 = np.array([[0.0000, 0.0000, 0.0000], [-0.5000, 0.5000, 0.0625], [0.0000, 0.0000, 0.1250], [-0.5000, 0.5000, 0.1875], [0.0000, 0.0000, 0.2500], [-0.5000, 0.5000, 0.3125],[0.0000, 0.0000, 0.3750], [-0.5000, 0.5000, -0.0625], [0.0000, 0.0000, -0.1250], [-0.5000, 0.5000, -0.1875], [0.0000, 0.0000, -0.2500], [-0.5000, 0.5000, -0.3125],[0.0000, 0.0000, -0.3750]])

nat_cell_slab13 = 13

nk_slab13 = [4, 4, 1]

XGChi0.Vis_tool(chi0rrslab13, Rslab13, A, B, C, nk_slab13, nat_cell_slab13, pos_redslab13, N=10000, isomin=3)

# Test Algorithm Part

In [2]:
dim = np.load("dim.npy")

In [3]:
dim

array([55, 55, 59])

In [2]:
filename = "Bulk2Atoms6o_DS1_SUS.nc"
#BUILD
chi0GG, ind_qG_to_vec, n1, n2, n3, ind_q_to_vec, ind_G_to_vec, G, nk = XGChi0.Build_Chi0GG(filename, "FromSym", omega = 0)
print(n1, n2, n3)
#TRANSFORM
#chi0rr = XGChi0.FFT_chi0_from_Mat(np.real(chi0GG), ind_qG_to_vec, 40, 40, 80, ind_q_to_vec, ind_G_to_vec, G, nk, opt2 = "Kaltak")
#chi0rr = np.load("chi0rr_slab5_2.npy")
#Max
#max_chi0rr = np.max(np.abs(np.real(chi0rr)))
#0
#zero_t = chi0rr[0, 0, 0, 0, 0, 0]


16
the initialization of the dictionnaries and gathering of the information about the valid vectors took 5.68062686920166 seconds
The initialisation of smallchi0GG took 2.5078511238098145 seconds
Sym ok
3.0824605801171856e-06
3.0824605801171856e-06
6.080699772913548e-14
6.080699772913548e-14
the building of chi0GG took  963.014307975769 seconds
43 43 49


In [176]:
chi0rr = XGChi0.FFT_chi0_from_Mat(np.real(chi0GG), ind_qG_to_vec, 40, 40, 80, ind_q_to_vec, ind_G_to_vec, G, nk, opt2 = "Kaltak")

Starting first FFT


KeyboardInterrupt: 

In [3]:
chi0rr = XGChi0.FFT_chi0_sizeadapt(np.real(chi0GG), ind_qG_to_vec, 72, 72, 60, 12, 12, 60, ind_q_to_vec, ind_G_to_vec, G, nk, opt2 = "Kaltak")

12 12 60
Starting first FFT
12 12 60
The first FFT took  238.13174605369568  seconds
Starting second FFT
-1.0
-0.9998842592592593
-0.9997685185185186
-0.9996527777777777
-0.999537037037037
-0.9994212962962963
-0.9993055555555556
-0.9991898148148148
-0.9990740740740741
-0.9989583333333333
-0.9988425925925926
-0.9987268518518518
-0.9986111111111111
-0.9984953703703704
-0.9983796296296297
-0.9982638888888888
-0.9981481481481481
-0.9980324074074074
-0.9979166666666667
-0.997800925925926
-0.9976851851851852
-0.9975694444444444
-0.9974537037037037
-0.997337962962963
-0.9972222222222222
-0.9971064814814815
-0.9969907407407408
-0.996875
-0.9967592592592592
-0.9966435185185185
-0.9965277777777778
-0.9964120370370371
-0.9962962962962963
-0.9961805555555555
-0.9960648148148148
-0.9959490740740741
-0.9958333333333333
-0.9957175925925926
-0.9956018518518519
-0.9954861111111111
-0.9953703703703703
-0.9952546296296296
-0.9951388888888889
-0.9950231481481482
-0.9949074074074074
-0.9947916666666666
-0.

In [171]:
print(chi0rr.shape)

(9, 9, 72, 40, 40, 80)


In [ ]:
np.save("chi0rr_slab5atoms6_ecut8", chi0rr)

In [3]:
chi0rr = np.load("chi0rr_bulk2atoms6.npy")

In [138]:
np.save("chi0rr_slab5_80pnt", chi0rr)

In [113]:
chi0rr.shape

(9, 9, 72, 40, 40, 80)

In [135]:
ngkpt = [6, 6, 6]
n1_go, n2_go, n3_go, n4_go, n5_go, n6_go = chi0rr.shape
X1_2D = np.linspace(0, ngkpt[0]*2.85, n4_go,endpoint = False)
X2_2D = np.linspace(0, ngkpt[1]*2.85, n5_go,endpoint = False)
X3_2D = np.linspace(0, ngkpt[2]*4.03, n6_go,endpoint = False)

""" X1R = np.linspace(0, 1, n1_go, endpoint = False)
X2R = np.linspace(0, 1, n2_go, endpoint = False)
X3R = np.linspace(0, 1, n3_go, endpoint = False)
 """

' X1R = np.linspace(0, 1, n1_go, endpoint = False)\nX2R = np.linspace(0, 1, n2_go, endpoint = False)\nX3R = np.linspace(0, 1, n3_go, endpoint = False)\n '

In [134]:
R_2D = [0, 0, 0]

In [155]:
Y1_2D = np.real(chi0rr[0, 0, 0, :, 0, 0])


In [156]:
l = Y1_2D.size
Y1_2D_000 = np.zeros((l))
l2 = math.floor(l/2)
l1 = l-1
Y1_2D_000[l2:l] = Y1_2D[0:l2]
Y1_2D_000[0:l2] = Y1_2D[l2:l]

In [157]:
Y1_2D3 = np.real(chi0rr[0, 0, 0, 0, 0, :])

In [158]:
l = Y1_2D3.size
Y1_2D4 = np.zeros((l))
l2 = math.floor(l/2)
l1 = l-1
Y1_2D4[l2:l] = Y1_2D3[0:l2]
Y1_2D4[0:l2] = Y1_2D3[l2:l]

In [159]:
Y2_2D = np.real(chi0rr[6, 6, 6, 6, :, 6])

In [160]:
l = Y2_2D.size
Y2_2D_666 = np.zeros((l))
l2 = math.floor(l/2)
l1 = l-1
Y2_2D_666[l2:l] = Y2_2D[0:l2]
Y2_2D_666[0:l2] = Y2_2D[l2:l]

In [161]:
Y3_2D = np.real(chi0rr[3, 3, 3, :, 3, 3])

In [162]:
l = Y1_2D.size
Y1_2D_333 = np.zeros((l))
l2 = math.floor(l/2)
l1 = l-1
Y1_2D_333[l2:l] = Y3_2D[0:l2]
Y1_2D_333[0:l2] = Y3_2D[l2:l]

In [111]:
Y1_2D = np.real(chi0rr[R_2D[0], R_2D[1], R_2D[2], :, R_2D[1], R_2D[2]])
Y2_2D = np.real(chi0rr[R_2D[0], R_2D[1], R_2D[2], R_2D[0], :, R_2D[2]])
Y3_2D = np.real(chi0rr[R_2D[0], R_2D[1], R_2D[2], R_2D[0], R_2D[1], :])

Y4_2D = np.real(chi0rr[R_2D[0], R_2D[1], R_2D[2], :, 0, 0])
Y5_2D = np.real(chi0rr[R_2D[0], R_2D[1], R_2D[2], 0, :, 0])
Y6_2D = np.real(chi0rr[R_2D[0], R_2D[1], R_2D[2], 0, 0, :])

Y1_2DK = np.real(chi0rr[:, R_2D[1], R_2D[2], R_2D[0], R_2D[1], R_2D[2]])
Y2_2DK = np.real(chi0rr[R_2D[0], :, R_2D[2], R_2D[0], R_2D[1], R_2D[2]])
Y3_2DK = np.real(chi0rr[R_2D[0], R_2D[1], :, R_2D[0], R_2D[1], R_2D[2]])

In [97]:
l = Y2_2D.size
Y2_2D_999 = np.zeros((l))
l2 = math.floor(l/2)
l1 = l-1
Y2_2D_999[l2:l] = Y1_2D[0:l2]
Y2_2D_999[0:l2] = Y1_2D[l2:l]

In [59]:
l = Y2_2D.size
Y2_2D_666 = np.zeros((l))
l2 = math.floor(l/2)
l1 = l-1
Y2_2D_666[l2:l] = Y1_2D[0:l2]
Y2_2D_666[0:l2] = Y1_2D[l2:l]

In [54]:
l = Y1_2D.size
Y1_2D_000 = np.zeros((l))
l2 = math.floor(l/2)
l1 = l-1
Y1_2D_000[l2:l] = Y1_2D[0:l2]
Y1_2D_000[0:l2] = Y1_2D[l2:l]

In [55]:
print(l)

72


In [64]:
l = Y1_2D.size
Y1_2D_333 = np.zeros((l))
l2 = math.floor(l/2)
l1 = l-1
Y1_2D_333[l2:l] = Y1_2D[0:l2]
Y1_2D_333[0:l2] = Y1_2D[l2:l]

In [154]:
maxchi = np.max(np.abs(np.real(chi0rr)))

In [132]:
trace1 = go.Scatter(x = X1_2D,y = Y1_2D,mode = "lines+markers")

trace2 = go.Scatter(x = X2_2D,y = Y2_2D,mode = "lines+markers")

trace3 = go.Scatter(x = X3_2D,y = Y3_2D,mode = "lines+markers")

trace7 = go.Scatter(x = X1_2D,y = Y2_2D,mode = "lines+markers")

trace8 = go.Scatter(x = X2R,y = Y2_2DK,mode = "lines+markers",name = "Axe1K")

trace9 = go.Scatter(x = X3R,y = Y3_2DK,mode = "lines+markers",name = "Axe2K")
#trace1, trace2, trace7, trace8,trace7, trace8,  trace9
data = [ trace1, trace2, trace3]
layout = dict(
    paper_bgcolor='rgba(0,0,0,0)',
    plot_bgcolor='rgba(0,0,0,0)',
)
fig = go.Figure(dict(data = data, layout = layout))
fig.show(dpi = 300)

In [165]:
trace1 = go.Scatter(x = X1_2D,y = Y1_2D_000/maxchi,mode = "lines+markers")

trace2 = go.Scatter(x = X2_2D,y = Y2_2D_666/maxchi,mode = "lines+markers")

trace3 = go.Scatter(x = X1_2D,y = Y1_2D_333/maxchi,mode = "lines+markers")

trace7 = go.Scatter(x = X3_2D,y = Y1_2D4/maxchi,mode = "lines+markers")

trace8 = go.Scatter(x = X2R,y = Y2_2DK,mode = "lines+markers",name = "Axe1K")

trace9 = go.Scatter(x = X3R,y = Y3_2DK,mode = "lines+markers",name = "Axe2K")
#trace1, trace2, trace7, trace8,trace7, trace8,  trace9
data = [ trace1, trace2, trace3]
layout = dict(
    paper_bgcolor='rgba(0,0,0,0)',
    plot_bgcolor='rgba(0,0,0,0)',
)
fig = go.Figure(dict(data = data, layout = layout))
fig.show(dpi = 300)

In [99]:
fig = go.Figure(dict(data = [trace1, trace2], layout = layout))
fig.show()

In [72]:
fig = go.Figure(dict(data = trace3, layout = layout))
fig.show()

In [82]:
radius = 2
charge_evol_prim = XGChi0.charge_evol(chi0rr, radius)

In [83]:
print(charge_evol_prim.shape)

(12, 12, 12)


In [84]:
charge_1 = charge_evol_prim[0, :, :]
charge_2 = charge_evol_prim[0, 0, :]
chi0rr_cut0 = np.concatenate((charge_1, [charge_2]), axis = 0)
print(chi0rr_cut0[:, 0].size)
charge_3 = chi0rr_cut0[:, 0]
chi0rr_cut = np.concatenate((chi0rr_cut0, np.transpose([charge_3])), axis = 1)
print(chi0rr_cut.shape)

13
(13, 13)


In [4]:
chi0rr_cut = XGChi0.charge_accul_cut(chi0rr, 2, "xz", 0)

Max charge accumulation =  40637.54445734927


In [52]:
#layout_prim = dict(title = 'Charge accumulation in a box of size '+str(2*radius+1)+' in the plane yz', xaxis= dict(title= 'z axis',ticklen= 5,zeroline= False), yaxis= dict(title= 'y axis',ticklen= 5,zeroline= False),)
#, layout = layout_prim
layout = dict(
    value = "viridis",
)
fig = go.Figure(data = go.Contour(z = np.real(chi0rr_cut)/np.max(np.abs(np.real(chi0rr_cut))), x = np.linspace(0, 4.03, 13), y = np.linspace(0, 2.85, 13), colorscale='teal', line_smoothing=0.85, contours_coloring='heatmap'))

fig.update_layout(
    autosize=False,
    width=800,
    height=570,
    )

fig.show(dpi = 300)

In [116]:
chi0rr_cut = XGChi0.charge_accul_cut(chi0rr, 2, "xy", 0)

Max charge accumulation =  40637.54445734927


In [117]:
layout_prim = dict(title = 'Charge accumulation in a box of size '+str(2*radius+1)+' in the plane yz',
              xaxis= dict(title= 'z axis',ticklen= 5,zeroline= False),
              yaxis= dict(title= 'y axis',ticklen= 5,zeroline= False),
             )
fig = go.Figure(data = go.Contour(z = np.real(chi0rr_cut)/np.max(np.abs(np.real(chi0rr_cut)))), layout = layout_prim)
fig.show()

In [104]:
print(chi0rr_cut[:, 6])

[-17979.8419065 -2.74410472e-13j -18900.88616188-4.17899200e-03j
 -21629.67456736+4.40881344e-04j -25831.8487584 +1.03663225e-02j
 -30576.151766  +1.98778153e-02j -34380.00465726+1.75275665e-02j
 -35855.55184374+8.92985338e-13j -34380.00465726-1.75275665e-02j
 -30576.151766  -1.98778153e-02j -25831.8487584 -1.03663225e-02j
 -21629.67456736-4.40881344e-04j -18900.88616188+4.17899200e-03j
 -17979.8419065 -2.74410472e-13j]


In [91]:
charge_test0 = chi0rr[0, 2, 3, -1, 1, 2] + chi0rr[0, 2, 3, -1, 1, 3] + chi0rr[0, 2, 3, -1, 1, 4] + chi0rr[0, 2, 3, -1, 2, 2] + chi0rr[0, 2, 3, -1, 2, 3] + chi0rr[0, 2, 3, -1, 2, 4] +chi0rr[0, 2, 3, -1, 3, 2] + chi0rr[0, 2, 3, -1, 3, 3] + chi0rr[0, 2, 3, -1, 3, 4]
charge_test1 = chi0rr[0, 2, 3, 0, 1, 2] + chi0rr[0, 2, 3, 0, 1, 3] + chi0rr[0, 2, 3, 0, 1, 4] + chi0rr[0, 2, 3, 0, 2, 2] + chi0rr[0, 2, 3, 0, 2, 3] + chi0rr[0, 2, 3, 0, 2, 4] +chi0rr[0, 2, 3, 0, 3, 2] + chi0rr[0, 2, 3, 0, 3, 3] + chi0rr[0, 2, 3, 0, 3, 4]
charge_test2 = chi0rr[0, 2, 3, 1, 1, 2] + chi0rr[0, 2, 3, 1, 1, 3] + chi0rr[0, 2, 3, 1, 1, 4] + chi0rr[0, 2, 3, 1, 2, 2] + chi0rr[0, 2, 3, 1, 2, 3] + chi0rr[0, 2, 3, 1, 2, 4] +chi0rr[0, 2, 3, 1, 3, 2] + chi0rr[0, 2, 3, 1, 3, 3] + chi0rr[0, 2, 3, 1, 3, 4]
charge_test0+charge_test1+charge_test2

(-18405.461929950547-0.08317719722723217j)

In [90]:
charge_test4 = chi0rr[0, 10, 3, -1, 9, 2] + chi0rr[0, 10, 3, -1, 9, 3] + chi0rr[0, 10, 3, -1, 9, 4] + chi0rr[0, 10, 3, -1, 10, 2] + chi0rr[0, 10, 3, -1, 10, 3] + chi0rr[0, 10, 3, -1, 10, 4] +chi0rr[0, 10, 3, -1, 11, 2] + chi0rr[0, 10, 3, -1, 11, 3] + chi0rr[0, 10, 3, -1, 11, 4]
charge_test5 = chi0rr[0, 10, 3, 0, 9, 2] + chi0rr[0, 10, 3, 0, 9, 3] + chi0rr[0, 10, 3, 0, 9, 4] + chi0rr[0, 10, 3, 0, 10, 2] + chi0rr[0, 10, 3, 0, 10, 3] + chi0rr[0, 10, 3, 0, 10, 4] +chi0rr[0, 10, 3, 0, 11, 2] + chi0rr[0, 10, 3, 0, 11, 3] + chi0rr[0, 10, 3, 0, 11, 4]
charge_test6 = chi0rr[0, 10, 3, 1, 9, 2] + chi0rr[0, 10, 3, 1, 9, 3] + chi0rr[0, 10, 3, 1, 9, 4] + chi0rr[0, 10, 3, 1, 10, 2] + chi0rr[0, 10, 3, 1, 10, 3] + chi0rr[0, 10, 3, 1, 10, 4] +chi0rr[0, 10, 3, 1, 11, 2] + chi0rr[0, 10, 3, 1, 11, 3] + chi0rr[0, 10, 3, 1, 11, 4]
charge_test4+charge_test5+charge_test6

(-18405.779820542568-0.0856794357716488j)

In [101]:
chi0rr[0, 10, 3, 0, 10, 3]

(-1188.0970528232565-0.0029328687919694383j)

In [102]:
chi0rr[0, 2, 3, 0, 2, 3]

(-1188.0834896453082-0.0036446557729393333j)

In [100]:
charge_test6


(-5674.610527962312-0.08031848397569583j)

In [98]:
charge_test4

(-5674.611988836205+0.022078761854015742j)

In [35]:
np.sum(chi0rr[0, 0, 0, :, :, :])

(-1.4210854715202004e-13+5.551115123125783e-17j)

In [36]:
chi0rr[0, 0, 0, 0, 0, 0]

(-142.9593206071159+0j)

In [169]:
print(max_chi0rr, zero_t, chi0rr.shape)

301.0547293901726 (-0.7640257208573636+0j) (9, 9, 72, 40, 40, 80)


In [20]:
np.max(np.abs(np.real(chi0rr)))

1354.1611164699068

In [21]:
np.max(np.abs(np.imag(chi0rr)))

0.05434289568442372

In [22]:
np.max(np.abs(np.real(chi0GG)))

0.0966932624578476

In [23]:
np.max(np.abs(np.imag(chi0GG)))

0.003025973914191127

In [25]:
chi0GG.shape

(216, 451, 451)

In [170]:
print(max_chi0rr, zero_t, chi0rr.shape)

301.0547293901726 (-0.7640257208573636+0j) (9, 9, 72, 40, 40, 80)


In [11]:
np.sum(chi0rr[0, 0, 0, :,:,:])

(4.263256414560601e-14+2.710505431213761e-20j)

In [131]:
0.2*72

14.4

In [26]:
sus_ncfile, kpoints, ng, nkpt, G = Ft.openfile("Bulk2Atoms6o_DS1_SUS.nc")

In [119]:
structure=abipy.core.structure.Structure.from_file("Bulk2Atomso_DS1_SUS.nc")
dict_struct = structure.to_abivars()
natom = dict_struct["natom"]
xred = dict_struct["xred"]
xred

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5]])

In [47]:
structure=abipy.core.structure.Structure.from_file("Bulk2Atomso_DS1_SUS.nc")
dict_struct = structure.to_abivars()
natom = dict_struct["natom"]
xred = dict_struct["xred"]
xred

array([[0. , 0. , 0. ],
       [0.5, 0.5, 0.5]])

In [11]:
Sym = abipy.core.symmetries.AbinitSpaceGroup.from_structure(structure)
SymRec = Sym.symrec

In [12]:
print(len(SymRec))

16


In [13]:
Trec = Sym.tnons
Trec

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [120]:
structure.visualize("vesta")

Writing data to: .xsf with fmt: xsf
Executing MacOSx open command: open -a vesta --args   /Users/acloots/Documents/GitHub/Thesis_SURFASCOPE/.xsf


0

In [28]:
nkpt = len(kpoints)

In [29]:
smallchi0 = np.zeros((nkpt, ng, ng), dtype = complex)
for i in range(nkpt):
    smallchi0[i] = sus_ncfile.reader.read_wggmat(kpoints[i]).wggmat[0]


In [32]:
for i in range(nkpt):
    print(i, np.amax(np.abs(np.imag(smallchi0[i, :, :]))))

0 9.034077375069671e-10
1 0.0006347534945234656
2 0.0007253153598867357
3 0.0008224844932556152
4 0.001234724186360836
5 0.000674895360134542
6 0.0009619079646654427
7 0.0008562825969420373
8 0.0017671978566795588
9 0.0003244261024519801
10 0.003025973914191127
11 0.0010486453538760543
12 0.0012320359237492085
13 0.0008699574391357601
14 0.0009766414295881987
15 0.0007150013698264956
16 0.0007228460744954646
17 0.0009872562950477004
18 0.000750829407479614
19 0.000921135360840708
20 0.000723032746464014
21 0.0013221799163147807
22 0.0005783977103419602
23 0.0005788636626675725
24 0.0011420409427955747
25 0.0008776671602390707
26 0.0006643441156484187
27 0.0006094624986872077
28 0.0007011177367530763
29 0.0003910729428753257
30 0.00031310724443756044
31 0.0011286524822935462
32 0.0012990857940167189
33 0.0008584759198129177
34 0.000809915887657553
35 0.0008390079019591212
36 0.0007793827680870891
37 0.0011086234590038657
38 0.0009715890628285706
39 0.0008471920154988766


In [31]:
for i in range(nkpt):
    print(np.amax(np.abs(np.real(smallchi0[i, :, :]))))

0.08608099073171616
0.09139485657215118
0.08971909433603287
0.09322773665189743
0.09002397954463959
0.09428337961435318
0.09242169559001923
0.08774500340223312
0.09564613550901413
0.08862963318824768
0.09504296630620956
0.09319095313549042
0.09324362874031067
0.09366466850042343
0.0966932624578476
0.09536471217870712
0.09130996465682983
0.09553748369216919
0.0926736444234848
0.09394460916519165
0.08303197473287582
0.09127215296030045
0.09358669817447662
0.09481211006641388
0.09306643158197403
0.09434812515974045
0.09295926988124847
0.09251043200492859
0.09176348149776459
0.09084592759609222
0.08420082926750183
0.08956301212310791
0.09298138320446014
0.0935053676366806
0.09491409361362457
0.09366004168987274
0.09153822809457779
0.09583481401205063
0.09195956587791443
0.0911632850766182


In [31]:
G1 = G[1]
G1opp = G[2]
G2 = G[3]
G2opp = G[4]
print(G1, G1opp, G2, G2opp)

[1 0 0] [-1  0  0] [0 1 0] [ 0 -1  0]


In [30]:
print(kpoints)

0) [+0.000, +0.000, +0.000], weight: 0.000
1) [+0.250, +0.000, +0.000], weight: 0.000
2) [+0.500, +0.000, +0.000], weight: 0.000
3) [+0.250, +0.250, +0.000], weight: 0.000
4) [+0.500, +0.250, +0.000], weight: 0.000
5) [+0.500, +0.500, +0.000], weight: 0.000
6) [+0.250, +0.250, +0.250], weight: 0.000
7) [+0.500, +0.250, +0.250], weight: 0.000
8) [+0.500, +0.500, +0.250], weight: 0.000
9) [+0.500, +0.500, +0.500], weight: 0.000


In [11]:
q = kpoints[5]
print(q)

[+0.500, +0.500, +0.000], weight: 0.000


In [29]:
print(smallchi0[5, 1, 3], smallchi0[5, 2, 4])

(-6.165073500596918e-06-9.540051593148746e-08j) (-2.6954508939525113e-05+3.67610969442822e-10j)


In [17]:
print(kpoints)

0) [+0.000, +0.000, +0.000], weight: 0.000
1) [+0.250, +0.000, +0.000], weight: 0.000
2) [+0.500, +0.000, +0.000], weight: 0.000
3) [+0.250, +0.250, +0.000], weight: 0.000
4) [+0.500, +0.250, +0.000], weight: 0.000
5) [+0.500, +0.500, +0.000], weight: 0.000


In [20]:
print(G[2], G[1], G[3], G[4])

[ 0  0 -1] [0 0 1] [0 0 2] [ 0  0 -2]


In [6]:
chi0GG = np.load("chi0GG_slab5.npy")

In [14]:
chi0GG, ind_qG_to_vec, n1, n2, n3, ind_q_to_vec, ind_G_to_vec, G, nk = XGChi0.Build_Chi0GG("Al_Slab5_Chi0o_DS1_SUS.nc", "FromSym", omega = 0)

45392
Basic Dict initialized
Dict with symmetry initialized
qGvec sorted
Dict of symmetry initialized


In [15]:
print(ind_q_to_vec)

{0: (0.0, 0.0, 0.0), 1: (1.0, 0.0, 0.0), 2: (2.0, 0.0, 0.0), 3: (1.0, 1.0, 0.0), 4: (2.0, 1.0, 0.0), 5: (2.0, 2.0, 0.0), 6: (-1.0, 0.0, 0.0), 7: (-1.0, -1.0, 0.0), 8: (2.0, -1.0, 0.0), 9: (0.0, 1.0, 0.0), 10: (0.0, 2.0, 0.0), 11: (-1.0, 1.0, 0.0), 12: (-1.0, 2.0, 0.0), 13: (0.0, -1.0, 0.0), 14: (1.0, -1.0, 0.0), 15: (1.0, 2.0, 0.0)}


In [14]:
print(chi0GG[5, 2, 4], chi0GG[5, 1, 3])

(-0.029592100530862808-9.027307235065507e-10j) (-0.029592100530862808-3.4965672718323404e-11j)


In [18]:
def filling(chi0GG):
    n4, n5, n6 = chi0GG.shape
    count = 0
    for i in range(n4):
        for j in range(n5):
            for k in range(n6):
                if chi0GG[i, j, k] != 0:
                    count += 1  
    return count/chi0GG.size

In [9]:
print(filling(chi0GG))

0.854843023958669


In [16]:
print(smallchi0[4])

[[-5.40128835e-02+3.15388415e-14j -3.04223951e-02+4.34621725e-08j
  -3.04223951e-02+4.42452013e-08j ... -8.53386427e-06-1.26166655e-09j
  -1.00771176e-05-3.64824060e-10j -7.72061867e-06-9.07137698e-10j]
 [-3.04223951e-02-4.34621725e-08j -5.34836426e-02-8.25716719e-13j
   5.33436844e-03-2.84928914e-10j ... -2.62129697e-06-1.31827804e-09j
  -1.68122665e-06-4.78884821e-10j -1.93610458e-06-2.22762052e-11j]
 [-3.04223951e-02-4.42452013e-08j  5.33436844e-03+2.84928914e-10j
  -5.34836426e-02+2.31296156e-13j ...  1.14066950e-06-1.03483298e-10j
  -9.02488352e-07-2.66164507e-10j  1.02540992e-06-8.84925966e-10j]
 ...
 [-8.53386427e-06+1.26166655e-09j -2.62129697e-06+1.31827804e-09j
   1.14066950e-06+1.03483298e-10j ... -9.97559482e-07-2.35594914e-18j
   1.20374693e-07-7.53698455e-14j  2.50407499e-08+9.15926189e-13j]
 [-1.00771176e-05+3.64824060e-10j -1.68122665e-06+4.78884821e-10j
  -9.02488352e-07+2.66164507e-10j ...  1.20374693e-07+7.53698455e-14j
  -2.00862360e-06-6.11565357e-18j  1.45833976e-

In [17]:
print(chi0GG[4])

[[-5.40128835e-02+3.15388415e-14j -3.04223951e-02+4.34621725e-08j
  -3.04223951e-02+4.42452013e-08j ...  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j -7.72061867e-06-9.07137698e-10j]
 [-3.04223951e-02-4.34621725e-08j -5.34836426e-02-8.25716719e-13j
   5.33436844e-03-2.84928914e-10j ...  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j -1.93610458e-06-2.22762052e-11j]
 [-3.04223951e-02-4.42452013e-08j  5.33436844e-03+2.84928914e-10j
  -5.34836426e-02+2.31296156e-13j ...  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j  1.02540992e-06-8.84925966e-10j]
 ...
 [ 0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j ...  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j ...  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j  0.00000000e+

In [26]:
count = 0
for i in range(ng):
    for j in range(ng):
        if chi0GG[4, i, j] != 0:
            count +=1
print(count/ng**2)

0.6990539560510695


In [146]:
filenamelist = {"Al_Bulk_nkpt4o_DS1_SUS.nc":["Al_R_prim_SUS_ngkpt4_ecuteps5_nband200", "Al_D_prim_SUS_ngkpt4_ecuteps5_nband200"], "Al_Bulko_DS1_SUS.nc":["Al_R_conv_SUS_ngkpt4_ecuteps14_nband150", "Al_D_conv_SUS_ngkpt4_ecuteps14_nband150"], "Al_Bulk_nkpt4o_DS4_SUS.nc":["Al_R_prim_SUS_ngkpt4_ecuteps17_nband200", "Al_D_prim_SUS_ngkpt4_ecuteps17_nband200"], "Al_Bulk_nkpt4o_DS6_SUS.nc":["Al_R_prim_SUS_ngkpt4_ecuteps25_nband200", "Al_D_prim_SUS_ngkpt4_ecuteps25_nband200"], "Al_Bulk_nkpt8o_DS2_SUS.nc":["Al_R_prim_SUS_ngkpt8_ecuteps17_nband150", "Al_D_prim_SUS_ngkpt8_ecuteps17_nband150"]}

In [151]:
for filename in filenamelist.keys():
    print("\n\nData for the file ", filename)
    chi0GG, ind_qG_to_vec, n1, n2, n3, ind_q_to_vec, ind_G_to_vec, G, nk = XGChi0.Build_Chi0GG(filename, "FromSymTest", omega = 0)
    percent_fill = filling(chi0GG)*100
    print("\nThe matrix chi0GG has a shape ", chi0GG.shape, " and is filled at ", percent_fill, "%")
    print("The max real of chi0GG value is ", np.max(np.abs(np.real(chi0GG))))
    print("The imag value of chi0GG is ", np.max(np.abs(np.imag(chi0GG))))
    print("The sum over all components of chi0GG is ", np.sum(chi0GG))
    print("The constant component of chi0GG is ", chi0GG[0, 0, 0])
    np.save(filenamelist[filename][0], chi0GG)
    chi0rr = XGChi0.FFT_chi0_from_Mat(np.real(chi0GG), ind_qG_to_vec, n1, n2, n3, ind_q_to_vec, ind_G_to_vec, G, nk, opt2 = "Kaltak")
    print("\nThe matrix chi0rr has a shape ", chi0rr.shape)
    print("The max real value of chi0rr is ", np.max(np.abs(np.real(chi0rr))))
    print("The imag real value of chi0rr is ", np.max(np.abs(np.imag(chi0rr))))
    print("The sum over all components chi0rr is ", np.sum(chi0rr))
    np.save(filenamelist[filename][1], chi0rr)



Data for the file  Al_Bulk_nkpt4o_DS1_SUS.nc
the initialization of the dictionnaries and gathering of the information about the valid vectors took 0.4907560348510742 seconds
The initialisation of smallchi0GG took 0.014528036117553711 seconds
the building of chi0GG took  1.8779819011688232 seconds

The matrix chi0GG has a shape  (64, 59, 59)  and is filled at  46.91315354783108 %
The max real of chi0GG value is  0.13829782605171204
The imag value of chi0GG is  5.393608262238558e-07
The sum over all components of chi0GG is  (-25.75586277302849+2.3318149382980794e-08j)
The constant component of chi0GG is  (-1.258613906429673e-07+1.4504860652603773e-25j)
Starting first FFT
The first FFT took  0.9886550903320312  seconds
Starting second FFT
The second FFT took  2.791167974472046  seconds

The matrix chi0rr has a shape  (5, 5, 5, 24, 24, 24)
The max real value of chi0rr is  115.02418125635711
The imag real value of chi0rr is  6.397894498517079e-05
The sum over all components chi0rr is  (-0

In [2]:
chi0GG_nsym1_nosym_Test, ind_qG_to_vec, n1, n2, n3, ind_q_to_vec, ind_G_to_vec, G, nk = XGChi0.Build_Chi0GG("Al_Slab5_ecuteps8_SUS.nc", "FromSymTest", omega = 0)

16
the initialization of the dictionnaries and gathering of the information about the valid vectors took 2.4674811363220215 seconds
The initialisation of smallchi0GG took 4.387864828109741 seconds
Sym ok
3.1255774501914857e-06
3.1255774501914857e-06
7.729907480161918e-14
7.729907480161918e-14
the building of chi0GG took  227.80202412605286 seconds


In [3]:
np.save("chi0GG_slab5_ecut8", chi0GG_nsym1_nosym_Test)

In [219]:
n4, n5, n6 = chi0GG_nsym1_nosym_Test.shape
count = 0
for i in range(n4):
    for j in range(n5):
        for k in range(n6):
            if chi0GG_nsym1_nosym_Test[i, j, k] != 0:
                count += 1
                

In [33]:
filling(chi0GG_nsym1_nosym_Test)

0.7020215824425008

In [50]:
16*2837**2

128777104

In [39]:
print(count)

5626384


In [220]:
print(count)

970879


In [ ]:
print(chi0GG_nsym1_nosym_Test)

In [4]:
chi0rr_nsym1_nosym_K = XGChi0.FFT_chi0_from_Mat(np.real(chi0GG_nsym1_nosym_Test), ind_qG_to_vec, n1, n2, n3, ind_q_to_vec, ind_G_to_vec, G, nk, opt2 = "Kaltak")

Starting first FFT
The first FFT took  85.91111397743225  seconds
Starting second FFT
The second FFT took  348.46496987342834  seconds


In [5]:
np.save("chi0rr_slab5_ecut8_2", chi0rr_nsym1_nosym_K)

In [18]:
chi0rr_nsym1_nosym_K = np.load("chi0rr_slab5_2.npy")

In [6]:
chi0rr_nsym1_nosym_K.shape

(8, 8, 50, 30, 30, 50)

In [7]:
np.amax(np.abs(np.imag(chi0rr_nsym1_nosym_K)))

7.453692939644665e-06

In [8]:
np.amax(np.abs(np.real(chi0rr_nsym1_nosym_K)))

298.5470842096533

In [14]:
ngkpt = [4, 4, 1]
n1_go, n2_go, n3_go, n4_go, n5_go, n6_go = chi0rr_nsym1_nosym_K.shape

In [15]:
X1_2D = np.linspace(0, ngkpt[0], n4_go,endpoint = False)
X2_2D = np.linspace(0, ngkpt[1], n5_go,endpoint = False)
X3_2D = np.linspace(0, ngkpt[2], n6_go,endpoint = False)

X1R = np.linspace(0, 1, n1_go, endpoint = False)
X2R = np.linspace(0, 1, n2_go, endpoint = False)
X3R = np.linspace(0, 1, n3_go, endpoint = False)

In [16]:
R_2D = [0, 0, 0]

In [17]:
Y1_2D = np.real(chi0rr_nsym1_nosym_K[R_2D[0], R_2D[1], R_2D[2], :, R_2D[1], R_2D[2]])
Y2_2D = np.real(chi0rr_nsym1_nosym_K[R_2D[0], R_2D[1], R_2D[2], R_2D[0], :, R_2D[2]])
Y3_2D = np.real(chi0rr_nsym1_nosym_K[R_2D[0], R_2D[1], R_2D[2], R_2D[0], R_2D[1], :])

Y4_2D = np.real(chi0rr_nsym1_nosym_K[R_2D[0], R_2D[1], R_2D[2], :, 0, 0])
Y5_2D = np.real(chi0rr_nsym1_nosym_K[R_2D[0], R_2D[1], R_2D[2], 0, :, 0])
Y6_2D = np.real(chi0rr_nsym1_nosym_K[R_2D[0], R_2D[1], R_2D[2], 0, 0, :])

Y1_2DK = np.real(chi0rr_nsym1_nosym_K[:, R_2D[1], R_2D[2], R_2D[0], R_2D[1], R_2D[2]])
Y2_2DK = np.real(chi0rr_nsym1_nosym_K[R_2D[0], :, R_2D[2], R_2D[0], R_2D[1], R_2D[2]])
Y3_2DK = np.real(chi0rr_nsym1_nosym_K[R_2D[0], R_2D[1], :, R_2D[0], R_2D[1], R_2D[2]])

In [18]:
trace1 = go.Scatter(
                    x = X1_2D,
                    y = Y1_2D,
                    mode = "lines+markers",
                    name = "Axe0"
                    )

trace2 = go.Scatter(
                    x = X2_2D,
                    y = Y2_2D,
                    mode = "lines+markers",
                    name = "Axe1"
                    )

trace3 = go.Scatter(
                    x = X3_2D,
                    y = Y3_2D,
                    mode = "lines+markers",
                    name = "Axe2"
                    )

trace4 = go.Scatter(
                    x = X1_2D,
                    y = Y4_2D,
                    mode = "lines+markers",
                    name = "Axe0_origin"
                    )

trace5 = go.Scatter(
                    x = X2_2D,
                    y = Y5_2D,
                    mode = "lines+markers",
                    name = "Axe1_origin"
                    )

trace6 = go.Scatter(
                    x = X3_2D,
                    y = Y6_2D,
                    mode = "lines+markers",
                    name = "Axe2_origin"
                    )

trace7 = go.Scatter(
                    x = X1R,
                    y = Y1_2DK,
                    mode = "lines+markers",
                    name = "Axe0K"
                    )

trace8 = go.Scatter(
                    x = X2R,
                    y = Y2_2DK,
                    mode = "lines+markers",
                    name = "Axe1K"
                    )

trace9 = go.Scatter(
                    x = X3R,
                    y = Y3_2DK,
                    mode = "lines+markers",
                    name = "Axe2K"
                    )



data = [trace1, trace2, trace3, trace4, trace5, trace6, trace7, trace8, trace9]
layout = dict(title = 'chi0(r, r\') with R ='+str(R_2D)+' for different directions',
              xaxis= dict(title= 'Number of unit cells',ticklen= 5,zeroline= False),
             )
fig = go.Figure(dict(data = data, layout = layout))
fig.show()

In [38]:
sus_ncfile = ScrFile("Al_Slab_GS_Chi0o_DS1_SUS.nc")
##Get the list of kpoints
##Get the number of frequencies
nw=sus_ncfile.reader.nw
##Get the number of G-vectors
ng=sus_ncfile.reader.ng 
##Get the number of kpoints
##Get the chi0 matrix of q=0 0 0
kpoints=sus_ncfile.reader.kpoints
chi0=sus_ncfile.reader.read_wggmat(kpoints[0])
chi0_mat = chi0.wggmat
print(len(kpoints))
print(chi0_mat.shape)

6
(5, 4523, 4523)


In [231]:
structure=abipy.core.structure.Structure.from_file("Al_Bulko_DS1_SUS.nc")

In [233]:
dict_struct = structure.to_abivars()
natom = dict_struct["natom"]
xred = dict_struct["xred"]
xred

array([[0. , 0. , 0. ],
       [0. , 0.5, 0.5],
       [0.5, 0. , 0.5],
       [0.5, 0.5, 0. ]])

In [227]:
xred = np.array([[ 0.        ,  0.        , -0.00595238],
       [-0.5       ,  0.5       ,  0.13690476],
       [ 0.        ,  0.        ,  0.2797619 ],
       [-0.5       ,  0.5       ,  0.42261905]])-np.array([[ 0.        ,  0.        , -0.00595238],
       [-0.5       ,  0.5       ,  -0.00595238],
       [ 0.        ,  0.        ,  -0.00595238],
       [-0.5       ,  0.5       ,  -0.00595238]])
xred

array([[0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.14285714],
       [0.        , 0.        , 0.28571428],
       [0.        , 0.        , 0.42857143]])

In [2]:
#Sym.symrec

In [34]:
chi0rrslab13 = XGChi0.FFT_chi0("Al_Slab_GS_Chi0o_DS1_SUS.nc")

16


KeyboardInterrupt: 